version: "3.8"
services:
    backend:
        build: .
        env_file:
            - .env
        container_name: geniva-backend
        ports:
            - "8080:8080"
        networks:
            - geniva-network
        depends_on:
            postgres:
                condition: service_healthy

    postgres:
        image: postgres:latest
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - 5432:5432
        container_name: postgres
        environment:
            POSTGRES_HOST: ${POSTGRES_HOST}
            POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DATABASE}
            POSTGRES_PORT: ${POSTGRES_PORT}
            PGUSER: ${POSTGRES_USER}
        networks:
            - geniva-network
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 30s

networks:
    geniva-network:
        driver: bridge
